FROM openjdk:8

ENV SPARK_VERSION=2.4.5
ENV SPARK_DOWNLOAD_VERSION="spark-${SPARK_VERSION}-bin-hadoop2.7"
ENV SPARK_UNTAR_FOLDER="spark-${SPARK_VERSION}"

RUN wget -nv https://archive.apache.org/dist/spark/spark-${SPARK_VERSION}/${SPARK_DOWNLOAD_VERSION}.tgz
RUN mkdir -p /opt/spark
RUN mv ${SPARK_DOWNLOAD_VERSION}.tgz /opt/spark

WORKDIR /opt/spark

RUN tar -xzf ${SPARK_DOWNLOAD_VERSION}.tgz --transform "s,${SPARK_DOWNLOAD_VERSION},${SPARK_UNTAR_FOLDER},"