FROM openjdk:8u252-jdk

ENV SPARK_VERSION=2.4.5
ENV SPARK_DOWNLOAD_VERSION="spark-${SPARK_VERSION}-bin-hadoop2.7"
ENV SPARK_UNTAR_FOLDER="spark-${SPARK_VERSION}"

RUN wget -nv https://archive.apache.org/dist/spark/spark-${SPARK_VERSION}/${SPARK_DOWNLOAD_VERSION}.tgz
RUN mkdir -p /opt/spark
RUN mv ${SPARK_DOWNLOAD_VERSION}.tgz /opt/spark

WORKDIR /opt/spark

RUN tar -xzf ${SPARK_DOWNLOAD_VERSION}.tgz --transform "s,${SPARK_DOWNLOAD_VERSION},${SPARK_UNTAR_FOLDER}," && rm ${SPARK_DOWNLOAD_VERSION}.tgz

RUN wget https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk/1.7.4/aws-java-sdk-1.7.4.jar && mv aws-java-sdk-1.7.4.jar /opt/spark/${SPARK_UNTAR_FOLDER}/jars/
RUN wget https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/2.7.2/hadoop-aws-2.7.2.jar && mv hadoop-aws-2.7.2.jar /opt/spark/${SPARK_UNTAR_FOLDER}/jars/

EXPOSE 8081 4040

# number of cores and memory are used within the script, they are passed when launching the container
COPY entrypoint_worker.sh ./
RUN chmod +x entrypoint_worker.sh

CMD ./entrypoint_worker.sh
